title:              iko's blog
email:              amitava.dev@proton.me
author:             ikouchiha47
domain:             ikouchiha47.github.io
baseurl:            ""
url:                ""
description: >- # this means to ignore newlines until "baseurl:"
  Yet another platform enginner, with a love for designing systems, writing tools, and hating third-party api integrations.

# Social Profiles
github_username:    ikouchiha47
linkedin_username:  amitavaag
disable_tracking:   true

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
